#!/usr/bin/env python
"""Persona provisioning — handbook page 17's launch sequence, the automated half.

The human creates the account and app password (2 minutes, permanently human,
per the handbook's touchpoint register). Everything after that is this script:

  1. avatar    — generated by the asset factory, judge-picked, saved to the bank
  2. profile   — display name + disclosed-AI bio applied via the API
  3. intro     — the cold-start post ("disclosure is the hook"), published & pinned

  python provision.py                # all steps
  python provision.py --skip-avatar  # profile + intro only (no fal needed)
  python provision.py --avatar-only  # (re)generate + set just the avatar
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

from studio import factory, publisher  # noqa: E402
from studio.brain import load_persona  # noqa: E402

BANK_DIR = Path(__file__).resolve().parent / "assets" / "bank"


def make_avatar(persona: dict) -> str:
    """4 candidates → vision judge picks → canonical face reference."""
    prompt = persona["profile"]["avatar_prompt"].strip()
    print("· generating 4 avatar candidates…")
    cands = factory.generate_images([prompt], BANK_DIR / "avatar-candidates", per_prompt=4)
    pick, reason = factory.judge_pick(
        cands, "Mara's profile avatar — warm, approachable, natural portrait; "
               "reject anatomical artifacts, dead eyes, plastic skin")
    print(f"· judge picked candidate {pick}: {reason}")
    chosen = Path(cands[pick]["path"])
    avatar_path = BANK_DIR / "avatar.jpg"
    avatar_path.write_bytes(chosen.read_bytes())
    print(f"· canonical face reference saved → {avatar_path}")
    return str(avatar_path)


def apply_profile(client, persona: dict, avatar_path: str | None,
                  pinned: tuple[str, str] | None):
    """Upsert app.bsky.actor.profile, preserving fields we don't manage."""
    from atproto import models

    repo = client.me.did
    existing, swap_cid = None, None
    try:
        got = client.com.atproto.repo.get_record(params={
            "repo": repo, "collection": "app.bsky.actor.profile", "rkey": "self"})
        existing, swap_cid = got.value, got.cid
    except Exception:
        pass

    avatar_blob = existing.avatar if existing else None
    if avatar_path:
        data = publisher._compress_image(avatar_path)
        avatar_blob = client.upload_blob(data).blob
        print("· avatar uploaded")

    pinned_ref = existing.pinned_post if existing else None
    if pinned:
        pinned_ref = models.ComAtprotoRepoStrongRef.Main(uri=pinned[0], cid=pinned[1])

    record = models.AppBskyActorProfile.Record(
        display_name=persona["profile"]["display_name"],
        description=persona["identity"]["bio"].strip(),
        avatar=avatar_blob,
        banner=existing.banner if existing else None,
        pinned_post=pinned_ref,
    )
    client.com.atproto.repo.put_record(models.ComAtprotoRepoPutRecord.Data(
        repo=repo, collection="app.bsky.actor.profile", rkey="self",
        record=record, swap_record=swap_cid))
    print(f"· profile applied: {persona['profile']['display_name']!r} + disclosed-AI bio")


def publish_intro(client, persona: dict) -> tuple[str, str]:
    """The cold-start post — disclosure as the hook — returned for pinning."""
    text = " ".join(persona["profile"]["intro_post"].split())
    resp = client.send_post(text=publisher._compose(text))
    rkey = resp.uri.split("/")[-1]
    print(f"· intro post published → https://bsky.app/profile/"
          f"{client.me.handle}/post/{rkey}")
    return resp.uri, resp.cid


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--skip-avatar", action="store_true")
    ap.add_argument("--avatar-only", action="store_true")
    args = ap.parse_args()

    persona = load_persona()
    client = publisher.login()
    print(f"provisioning @{client.me.handle} as “{persona['identity']['name']}”")

    avatar_path = None
    if not args.skip_avatar:
        try:
            avatar_path = make_avatar(persona)
        except Exception as e:
            if args.avatar_only:
                raise
            print(f"! avatar skipped ({str(e)[:100]}) — rerun with --avatar-only later")

    if args.avatar_only:
        apply_profile(client, persona, avatar_path, pinned=None)
        print("done — avatar refreshed.")
        return 0

    pinned = publish_intro(client, persona)
    apply_profile(client, persona, avatar_path, pinned=pinned)
    print(f"done — https://bsky.app/profile/{client.me.handle}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
