#!/usr/bin/env python
"""Persona provisioning — handbook page 17's launch sequence, the automated half.

The human creates the account and app password (2 minutes, permanently human,
per the handbook's touchpoint register). Everything after that is this script:

  1. avatar    — generated by the asset factory, judge-picked, saved to the bank
  2. profile   — display name + disclosed-AI bio applied via the API
  3. intro     — the cold-start post ("disclosure is the hook"), published & pinned

  python provision.py                # all steps
  python provision.py --skip-avatar  # profile + intro only (no fal needed)
  python provision.py --avatar-only  # (re)generate + set just the avatar
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

from studio import factory, publisher  # noqa: E402
from studio import persona as persona_cfg  # noqa: E402

BANK_DIR = Path(__file__).resolve().parent / "assets" / "bank"


def make_avatar(persona: dict) -> str:
    """4 candidates → vision judge picks → the persona's canonical avatar.

    The judging criteria are derived from the persona rather than hardcoded:
    one persona's avatar is a portrait, another's is a corner of a room, and a
    judge told to look for a warm face would reject the right image."""
    prompt = persona["profile"]["avatar_prompt"].strip()
    name = persona["identity"]["name"]
    pid = persona.get("id", "persona")
    print(f"· generating 4 avatar candidates for {name}…")
    cands = factory.generate_images([prompt], BANK_DIR / f"{pid}-avatar-candidates",
                                    per_prompt=4)
    pick, reason = factory.judge_pick(
        cands, f"{name}'s profile avatar. It must match this brief: {prompt}. "
               "It also has to survive a small circular crop, so favour one clear "
               "centered subject and a calm background. Reject anything with "
               "readable text, logos, distorted shapes or anatomical artifacts.")
    print(f"· judge picked candidate {pick}: {reason}")
    chosen = Path(cands[pick]["path"])
    avatar_path = BANK_DIR / f"{pid}-avatar.jpg"
    avatar_path.write_bytes(chosen.read_bytes())
    print(f"· canonical avatar saved → {avatar_path}")
    return str(avatar_path)


def apply_profile(client, persona: dict, avatar_path: str | None,
                  pinned: tuple[str, str] | None):
    """Upsert app.bsky.actor.profile, preserving fields we don't manage."""
    from atproto import models

    repo = client.me.did
    existing, swap_cid = None, None
    try:
        got = client.com.atproto.repo.get_record(params={
            "repo": repo, "collection": "app.bsky.actor.profile", "rkey": "self"})
        existing, swap_cid = got.value, got.cid
    except Exception:
        pass

    avatar_blob = existing.avatar if existing else None
    if avatar_path:
        data = publisher._compress_image(avatar_path)
        avatar_blob = client.upload_blob(data).blob
        print("· avatar uploaded")

    pinned_ref = existing.pinned_post if existing else None
    if pinned:
        pinned_ref = models.ComAtprotoRepoStrongRef.Main(uri=pinned[0], cid=pinned[1])

    # `bot` is one of the AT Protocol's self-applicable global label values and
    # the profile flag Bluesky's own bot guide asks automated accounts to set.
    # Bluesky's guidelines never require it — which is exactly why setting it
    # matters: it is the one machine-readable, affirmative good-faith signal an
    # automated account can attach to itself, on a platform where authenticity
    # findings take down accounts rather than posts.
    labels = models.ComAtprotoLabelDefs.SelfLabels(
        values=[models.ComAtprotoLabelDefs.SelfLabel(val="bot")])

    record = models.AppBskyActorProfile.Record(
        display_name=persona["profile"]["display_name"],
        description=persona["identity"]["bio"].strip(),
        avatar=avatar_blob,
        banner=existing.banner if existing else None,
        pinned_post=pinned_ref,
        labels=labels,
    )
    client.com.atproto.repo.put_record(models.ComAtprotoRepoPutRecord.Data(
        repo=repo, collection="app.bsky.actor.profile", rkey="self",
        record=record, swap_record=swap_cid))
    print(f"· profile applied: {persona['profile']['display_name']!r} + disclosed-AI bio"
          " + self-label 'bot'")


def publish_intro(client, persona: dict) -> tuple[str, str]:
    """The cold-start post — disclosure as the hook — returned for pinning."""
    text = " ".join(persona["profile"]["intro_post"].split())
    resp = client.send_post(text=publisher._compose(text, persona_id=persona.get("id")))
    rkey = resp.uri.split("/")[-1]
    print(f"· intro post published → https://bsky.app/profile/"
          f"{client.me.handle}/post/{rkey}")
    return resp.uri, resp.cid


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--skip-avatar", action="store_true")
    ap.add_argument("--avatar-only", action="store_true")
    ap.add_argument("--persona", default="",
                    help="which persona's profile to apply (config/personas/*.yaml)")
    args = ap.parse_args()

    persona = persona_cfg.load(args.persona.strip() or None)
    client = publisher.login()
    print(f"provisioning @{client.me.handle} as “{persona['identity']['name']}”")

    avatar_path = None
    if not args.skip_avatar:
        try:
            avatar_path = make_avatar(persona)
        except Exception as e:
            if args.avatar_only:
                raise
            print(f"! avatar skipped ({str(e)[:100]}) — rerun with --avatar-only later")

    if args.avatar_only:
        apply_profile(client, persona, avatar_path, pinned=None)
        print("done — avatar refreshed.")
        return 0

    pinned = publish_intro(client, persona)
    apply_profile(client, persona, avatar_path, pinned=pinned)
    print(f"done — https://bsky.app/profile/{client.me.handle}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
